services:
    david63.resetregdate.admin.controller:
        class: david63\resetregdate\controller\admin_controller
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@language'			
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@david63.resetregdate.core.functions'
            - '%tables%'
            - '%core.root_path%ext/david63/resetregdate/adm/style/images'

    david63.resetregdate.core.functions:
        class: david63\resetregdate\core\functions
        arguments:
            - '@ext.manager'

    _defaults:
        public: true
