imports:
    - { resource: phpbb_tables.yml }

services:
    david63.resetregdate.admin.controller:
        class: david63\resetregdate\controller\admin_controller
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@language'			
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@david63.resetregdate.core.functions'
            - '%tables%'

    david63.resetregdate.core.functions:
        class: david63\resetregdate\core\functions
        arguments:
            - '@ext.manager'
